module.exports = [
  { Name: "Darth Vader",
    Fictional: "Yes",
    Alive: "No",
    Politician: "Yes",
    Hair: "No",
    Moustache: "No",
    src: "./images/DarthVader.jpg",
  },
  { Name: "Ming The Merciless",
    Fictional: "Yes",
    Alive: "Yes",
    Politician: "Yes",
    Hair: "No",
    Moustache: "yes",
    src: "./images/MingTheMerciless.jpg",
  },
  { Name: "Skeletor",
    Fictional: "Yes",
    Alive: "Yes",
    Politician: "No",
    Hair: "No",
    Moustache: "No",
    src: "./images/Skeletor.jpg",
  },
  { Name: "Hitler",
    Fictional: "No",
    Alive: "No",
    Politician: "Yes",
    Hair: "Yes",
    Moustache: "Yes",
    src: "./images/Hitler.jpg",
  },
  { Name: "Stalin",
    Fictional: "No",
    Alive: "No",
    Politician: "Yes",
    Hair: "Yes",
    Moustache: "Yes",
    src: "./images/Stalin.jpg",
  },
  { Name: "Trump",
    Fictional: "No",
    Alive: "Yes",
    Politician: "Yes",
    Hair: "Yes",
    Moustache: "No",
    src: "./images/Trump.jpg",
  },
  { Name: "Joffrey",
    Fictional: "Yes",
    Alive: "No",
    Politician: "Yes",
    Hair: "Yes",
    Moustache: "No",
    src: "./images/Joffrey.jpg",
  },
  { Name: "Dr Doom",
    Fictional: "Yes",
    Alive: "Yes",
    Politician: "Yes",
    Hair: "No",
    Moustache: "No",
    src: "./images/DrDoom.jpg",
  },
  { Name: "Justin Bieber",
    Fictional: "No",
    Alive: "Yes",
    Politician: "No",
    Hair: "Yes",
    Moustache: "No",
    src: "./images/JustinBieber.jpg",
  },
  { Name: "Mumm-Ra",
    Fictional: "Yes",
    Alive: "Yes",
    Politician: "No",
    Hair: "No",
    Moustache: "No",
    src: "./images/Mumm-Ra.jpg",
  },
  { Name: "M Bison",
    Fictional: "Yes",
    Alive: "Yes",
    Politician: "Yes",
    Hair: "Yes",
    Moustache: "No",
    src: "./images/Mbison.jpg",
  },
  { Name: "Katie Hopkins",
    Fictional: "No",
    Alive: "Yes",
    Politician: "No",
    Hair: "Yes",
    Moustache: "No",
    src: "./images/Hopkins.jpg",
  },
  { Name: "Jon Snow",
    Fictional: "Yes",
    Alive: "Yes",
    Politician: "No",
    Hair: "Yes",
    Moustache: "No",
    src: "./images/JonSnow.jpg",
  },
  { Name: "Maria Carey",
    Fictional: "No",
    Alive: "Yes",
    Politician: "No",
    Hair: "Yes",
    Moustache: "No",
    src: "./images/mariah-carey.jpg",
  },
  { Name: "George Osborne",
    Fictional: "No",
    Alive: "Yes",
    Politician: "Yes",
    Hair: "Yes",
    Moustache: "No",
    src: "./images/osborne.jpg",
  },
  { Name: "Simon Cowell",
    Fictional: "No",
    Alive: "Yes",
    Politician: "No",
    Hair: "Yes",
    Moustache: "No",
    src: "./images/Simon-Cowell.jpg",
  },
  { Name: "Thanos",
    Fictional: "Yes",
    Alive: "Yes",
    Politician: "No",
    Hair: "No",
    Moustache: "Moustache",
    src: "./images/thanos.png",
  },
  { Name: "Thatcher",
    Fictional: "No",
    Alive: "No",
    Politician: "Yes",
    Hair: "Yes",
    Moustache: "No",
    src: "./images/Thatcher.jpg",
  },
  { Name: "Zelda",
    Fictional: "Yes",
    Alive: "Yes",
    Politician: "Yes",
    Hair: "Yes",
    Moustache: "No",
    src: "./images/zelda.jpeg",
  }
]