module.exports = [
  { id:1,
    Name: "Darth Vader",
    Politician: "Yes",
    Moustache: "No",
    Mask: "Yes",
    Hair: "No",
    Nationality: "Tatooinian",
    src: "./images/DarthVader.jpg",
  },
  { id:2,
    Name: "Ming The Merciless",
    Politician: "Yes",
    Moustache: "Yes",
    Mask: "No",
    Hair: "Yes",
    Nationality: "Mongolian",
    src: "./images/MingTheMerciless.jpg",
  },
  { id:3,
    Name: "Skeletor",
    Politician: "No",
    Moustache: "No",
    Mask: "No",
    Hair: "No",
    Nationality: "Eternian",
    src: "./images/Skeletor.jpg",
  },
  { id:4,
    Name: "Hitler",
    Politician: "Yes",
    Moustache: "Yes",
    Mask: "No",
    Hair: "Yes",
    Nationality: "German",
    src: "./images/Hitler.jpg",
  },
  { id:5,
    Name: "Stalin",
    Politician: "Yes",
    Moustache: "Yes",
    Mask: "No",
    Hair: "Yes",
    Nationality: "Russian",
    src: "./images/Stalin.jpg",
  },
  { id:6,
    Name: "Trump",
    Politician: "Yes",
    Moustache: "No",
    Mask: "No",
    Hair: "Yes",
    Nationality: "American",
    src: "./images/Trump.jpg",
  },
  { id:7,
    Name: "Joffrey",
    Politician: "Yes",
    Moustache: "No",
    Mask: "No",
    Hair: "Yes",
    Nationality: "Westerosi",
    src: "./images/Joffrey.jpg",
  },
  { id:8,
    Name: "Dr Doom",
    Politician: "Yes",
    Moustache: "No",
    Mask: "Yes",
    Hair: "No",
    Nationality: "Latverian",
    src: "./images/DrDoom.jpg",
  },
  { id:9,
    Name: "Justin Bieber",
    Politician: "No",
    Moustache: "No",
    Mask: "No",
    Hair: "Yes",
    Nationality: "Canada",
    src: "./images/JustinBieber.jpg",
  },
  { id:10,
    Name: "Mumm-Ra",
    Politician: "No",
    Moustache: "No",
    Mask: "No",
    Hair: "No",
    Nationality: "Thunderian",
    src: "./images/Mumm-Ra.jpg",
  },
  { id:11,
    Name: "M Bison",
    Politician: "Yes",
    Moustache: "No",
    Mask: "No",
    Hair: "Yes",
    Nationality: "Bisonian",
    src: "./images/Mbison.jpg",
  },
  { id:12,
    Name: "Katie Hopkins",
    Politician: "No",
    Moustache: "No",
    Mask: "No",
    Hair: "Yes",
    Nationality: "British",
    src: "./images/Hopkins.jpg",
  },
  { id:13,
    Name: "Jon Snow",
    Politician: "Yes",
    Moustache: "Yes",
    Mask: "No",
    Hair: "Yes",
    Nationality: "Westerosian",
    src: "./images/JonSnow.jpg",
  },
  { id:14,
    Name: "Maria Carey",
    Politician: "No",
    Moustache: "No",
    Mask: "No",
    Hair: "Yes",
    Nationality: "American",
    src: "./images/mariah-carey.jpg",
  },
  { id:15,
    Name: "George Osborne",
    Politician: "Yes",
    Moustache: "No",
    Mask: "No",
    Hair: "Yes",
    Nationality: "British",
    src: "./images/osborne.jpg",
  },
  { id:16,
    Name: "Simon Cowell",
    Politician: "No",
    Moustache: "No",
    Mask: "No",
    Hair: "Yes",
    Nationality: "British",
    src: "./images/Simon-Cowell.jpg",
  },
  { id:17,
    Name: "Thanos",
    Politician: "No",
    Moustache: "No",
    Mask: "No",
    Hair: "No",
    Nationality: "Titanian",
    src: "./images/thanos.png",
  },
  { id:18,
    Name: "Thatcher",
    Politician: "Yes",
    Moustache: "No",
    Mask: "No",
    Hair: "Yes",
    Nationality: "British",
    src: "./images/Thatcher.jpg",
  },
  { id:19,
    Name: "Zelda",
    Politician: "Yes",
    Moustache: "No",
    Mask: "No",
    Hair: "Yes",
    Nationality: "Outer Space",
    src: "./images/zelda.jpeg",
  }
]