module.exports = [
  { Name: "Darth Vader",
    Politician: "Yes",
    Moustache: "No",
    Mask: "Yes",
    Hair: "No",
    Nationality: "Tatooinian",
    src: "http://www.sideshowtoy.com/photo.php?sku=1000763",
  },
  { Name: "Ming The Merciless",
    Politician: "Yes",
    Moustache: "Yes",
    Mask: "No",
    Hair: "Yes",
    Nationality: "Mongolian",
    src: "https://pbs.twimg.com/profile_images/3576260859/8031c96317a7ffb8cefa7d3578918e20.jpeg",
  },
  { Name: "Skeletor",
    Politician: "No",
    Moustache: "No",
    Mask: "No",
    Hair: "No",
    Nationality: "Eternian",
    src: "http://www.tshirtvortex.net/wp-content/uploads/2016/04/drinkingproblems.jpg",
  },
  { Name: "Hitler",
    Politician: "Yes",
    Moustache: "Yes",
    Mask: "No",
    Hair: "Yes",
    Nationality: "German",
    src: "http://f.tqn.com/y/history1900s/1/W/v/Q/1/Hitlerseated2.jpg",
  },
  { Name: "Stalin",
    Politician: "Yes",
    Moustache: "Yes",
    Mask: "No",
    Hair: "Yes",
    Nationality: "Russian",
    src: "http://i.dailymail.co.uk/i/pix/2015/06/18/21/29C1CD9A00000578-3130307-image-m-5_1434660552551.jpg",
  },
  { Name: "Trump",
    Politician: "Yes",
    Moustache: "No",
    Mask: "No",
    Hair: "Yes",
    Nationality: "American",
    src: "https://pixel.nymag.com/imgs/daily/following/2016/01/27/27-trump-cowboy.w190.h190.2x.jpg",
  },
  { Name: "Joffrey",
    Politician: "Yes",
    Moustache: "No",
    Mask: "No",
    Hair: "Yes",
    Nationality: "Westerosi",
    src: "http://vignette2.wikia.nocookie.net/game-of-thrones-le-trone-de-fer/images/8/89/Promo_(Joffrey)_Saison_4_(3).jpg/revision/latest/top-crop/width/240/height/240?cb=20160424205916&path-prefix=fr",
  },
  { Name: "Dr Doom",
    Politician: "Yes",
    Moustache: "No",
    Mask: "Yes",
    Hair: "No",
    Nationality: "Latverian",
    src: "http://images-cdn.moviepilot.com/images/c_scale,h_1200,w_1600/t_mp_quality/n3bhgbdah6afarpbehs7/could-anyone-actually-defeat-dr-doom-494013.jpg",
  },
  { Name: "Justin Bieber",
    Politician: "No",
    Moustache: "No",
    Mask: "No",
    Hair: "Yes",
    Nationality: "Canada",
    src: "http://cdn4.thr.com/sites/default/files/2014/01/justin_bieber_mugshot.jpg",
  },
  { Name: "Mumm-Ra",
    Politician: "No",
    Moustache: "No",
    Mask: "No",
    Hair: "No",
    Nationality: "Thunderian",
    src: "http://65.media.tumblr.com/tumblr_m6vp4wwwHi1rawb5do1_500.jpg",
  }
]