# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 84d0bd79630c91f0bed18b2638668e3561f2272338d9646c04321fc386666c8d3bcb6bad1f3ad4170fbb52808ee63b508395e952b223b700bd12b25188163ba8

test:
  secret_key_base: d890dac88bda9f0e9d2729269d0da9d3d1721ea62cf8c5901de84c7d3c07a33aac68b0a4bd0c487f2969e275a8f5bfbf4e308e4ba1fa6366a3ade9a0f65b108d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
