# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c73b2166196d7943e7d835a87dfaf0fc6265cbf02eeb7f78d2c08fca55071079f5e07318b1ce3691dd797eafaa08b9d9699d107526b0df0a7a5e5a697b382820

test:
  secret_key_base: 8ab912371e5c7385580807a813aab7c3e89f1138c51bc78a621d179827dc826b2504b39f7744ed081a8115cf1f906dcd474a8dd1b3180626ee13fd645f19239e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
